# TODO: merge with one in root
# include ../../.env

shopify-gqlgenc:
	@../../../../../dev/bin/gqlgenc


# TODO: pass acces token through env
# @export SHOPIFY_ADMIN_ACCESS_TOKEN=${SHOPIFY_ADMIN_ACCESS_TOKEN}