---
version: "3.8"

services:
  app:
    build:
      context: ./dev/containers/app
    ports:
      - ${PORT}:8080
    volumes:
      - .:/go/src/github.com/Pochirify/pochirify-backend:cached
      - /Users/apple/go/pkg/mod:/go/pkg/mod:cached
    environment:
      PORT: 8080
      GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
      SPANNER_INSTANCE_ID: "${SPANNER_INSTANCE_ID}"
      SPANNER_DATABASE_ID: "${SPANNER_DATABASE_ID}"

      FINCODE_API_KEY: "${FINCODE_API_KEY}"
      FINCODE_BASE_URL: "${FINCODE_BASE_URL}"
      IS_PAYPAY_PRODUCTION: "${IS_PAYPAY_PRODUCTION}"
      PAYPAY_API_KEY_ID: "${PAYPAY_API_KEY_ID}"
      PAYPAY_API_SECRET: "${PAYPAY_API_SECRET}"
      PAYPAY_MERCHANT_ID: "${PAYPAY_MERCHANT_ID}"
      PAYPAY_REDIRECT_URL: "${PAYPAY_REDIRECT_URL}"

      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
    working_dir: /go/src/github.com/Pochirify/pochirify-backend
    command: go run .
