---
version: "3.8"

services:
  app:
    build:
      context: ./dev/containers/app
    ports:
      - ${PORT}:8080
    volumes:
      - .:/go/src/github.com/Pochirify/pochirify-backend:cached
      - /Users/apple/go/pkg/mod:/go/pkg/mod:cached
    environment:
      PORT: 8080
      GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
      SPANNER_INSTANCE_ID: "${SPANNER_INSTANCE_ID}"
      SPANNER_DATABASE_ID: "${SPANNER_DATABASE_ID}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
    working_dir: /go/src/github.com/Pochirify/pochirify-backend
    command: go run .
