// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graqhql

type AddressInput struct {
	Zip        string  `json:"zip"`
	Prefecture string  `json:"prefecture"`
	AddressOne string  `json:"addressOne"`
	AddressTwo *string `json:"addressTwo"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}

type PaypayQRCodeInput struct {
	EmailAddress     string        `json:"emailAddress"`
	PhoneNumber      string        `json:"phoneNumber"`
	Address          *AddressInput `json:"address"`
	Amount           int           `json:"amount"`
	OrderDescription string        `json:"orderDescription"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Todo *Todo  `json:"todo"`
}

type CreatePaypayQRCodePayload struct {
	URL      string `json:"url"`
	DeepLink string `json:"deepLink"`
}
