// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AddressInput struct {
	Zip        string  `json:"zip"`
	Prefecture string  `json:"prefecture"`
	AddressOne string  `json:"addressOne"`
	AddressTwo *string `json:"addressTwo"`
}

type AllActiveVariantGroupIDs struct {
	Ids []string `json:"ids"`
}

type DeliveryTimeRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}

type PaypayQRCodeInput struct {
	EmailAddress     string        `json:"emailAddress"`
	PhoneNumber      string        `json:"phoneNumber"`
	Address          *AddressInput `json:"address"`
	Amount           int           `json:"amount"`
	OrderDescription string        `json:"orderDescription"`
}

type Product struct {
	ID       string   `json:"id"`
	Title    string   `json:"title"`
	Price    int      `json:"price"`
	Contents []string `json:"contents"`
	ImageURL string   `json:"imageURL"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Todo *Todo  `json:"todo"`
}

type VariantGroup struct {
	ID                  string             `json:"id"`
	Title               string             `json:"title"`
	ImageURLs           []string           `json:"imageURLs"`
	DeliveryTimeRange   *DeliveryTimeRange `json:"deliveryTimeRange"`
	FaqImageURL         *WebpPngImageURL   `json:"faqImageURL"`
	DescriptionImageURL *WebpPngImageURL   `json:"descriptionImageURL"`
	BadgeImageURL       string             `json:"badgeImageURL"`
}

type VariantGroupDetail struct {
	VariantGroup *VariantGroup `json:"variantGroup"`
	Variants     []*Product    `json:"variants"`
}

type WebpPngImageURL struct {
	WebpURL string `json:"webpURL"`
	PngURL  string `json:"pngURL"`
}

type CreatePaypayQRCodePayload struct {
	URL      string `json:"url"`
	DeepLink string `json:"deepLink"`
}
